# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Auto Southwest Check-In"
version: "1.0.0"
slug: "auto_southwest_check_in"
description: "Automatically check in to Southwest flights using jdholtz/auto-southwest-check-in."
url: "https://github.com/johnser/ha-repo/"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
init: false
map:
  - share:rw
  
options:
  SOUTHWEST_USERNAME: ""
  SOUTHWEST_PASSWORD: ""
  CONFIRMATION_NUMBER: ""
  PUSHOVER_USER_KEY: ""
  PUSHOVER_APP_KEY: ""
  TIMEZONE: "UTC"

schema:
  SOUTHWEST_USERNAME: "str"
  SOUTHWEST_PASSWORD: "str"
  CONFIRMATION_NUMBER: "str"
  PUSHOVER_USER_KEY: "str"
  PUSHOVER_APP_KEY: "str"
  TIMEZONE: "str"

# This is the local Docker image name that Home Assistant will build
image: "local/auto_southwest_check_in"


