name: "Auto Southwest Check-In"
version: "1.1.0"
slug: "auto_southwest_check_in"
description: "Automatically check in to Southwest flights using jdholtz/auto-southwest-check-in."
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: "application"
boot: "manual"

# IMPORTANT: We do NOT specify an "image" here, so the Supervisor will build locally.
# image: "local/auto_southwest_check_in"

options:
  SOUTHWEST_USERNAME: ""
  SOUTHWEST_PASSWORD: ""
  CONFIRMATION_NUMBER: ""
  PUSHOVER_USER_KEY: ""
  PUSHOVER_APP_KEY: ""
  TIMEZONE: "UTC"

schema:
  SOUTHWEST_USERNAME: "str"
  SOUTHWEST_PASSWORD: "str"
  CONFIRMATION_NUMBER: "str"
  PUSHOVER_USER_KEY: "str"
  PUSHOVER_APP_KEY: "str"
  TIMEZONE: "str"
