name: "Auto Southwest Check-In Repository"
url: "https://github.com/johnser/ha-repo"
maintainer: "johnser"
description: "Home Assistant Add-on Repository for automatically checking in to Southwest flights"
homeassistant: "2023.2.0"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
